/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package App;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JScrollPane;

/**
 *
 * @author Asus
 */
public class addNewQuestion extends javax.swing.JFrame {

    /**
     * Creates new form addNewQuestion
     */
    public addNewQuestion() {
        initComponents();
        
        //set background color
        getContentPane().setBackground(Color.white);
        
//        RoundedTextArea textArea = new RoundedTextArea();
//        textArea.setPreferredSize(new Dimension(300, 200));
//        textArea.setText("This is a rounded edge text area.\nYou can type here.");
//        JScrollPane scrollPane = new JScrollPane(textArea);
//
//        getContentPane().add(scrollPane, BorderLayout.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtnum = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtID = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        opt4Field = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        rad1 = new javax.swing.JRadioButton();
        rad2 = new javax.swing.JRadioButton();
        rad3 = new javax.swing.JRadioButton();
        rad4 = new javax.swing.JRadioButton();
        questionField = new javax.swing.JTextField();
        opt2Field = new javax.swing.JTextField();
        opt1Field = new javax.swing.JTextField();
        opt3Field = new javax.swing.JTextField();
        OKButton = new App.ButtonCustom();
        backButton = new App.ButtonCustom();

        jLabel4.setFont(new java.awt.Font("Montserrat SemiBold", 0, 24)); // NOI18N
        jLabel4.setText("Question");

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setBounds(new java.awt.Rectangle(0, 0, 540, 600));
        setFocusable(false);
        setForeground(java.awt.Color.white);
        setMaximumSize(new java.awt.Dimension(540, 600));
        setMinimumSize(new java.awt.Dimension(540, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Montserrat SemiBold", 0, 36)); // NOI18N
        jLabel1.setText("<html><u>ADD QUESTION</u></html>");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 13, -1, -1));

        txtnum.setFont(new java.awt.Font("Montserrat SemiBold", 0, 24)); // NOI18N
        txtnum.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtnum.setText("[num]");
        getContentPane().add(txtnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 75, -1, -1));

        jLabel3.setFont(new java.awt.Font("Montserrat SemiBold", 0, 24)); // NOI18N
        jLabel3.setText("Question");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 75, -1, -1));

        txtID.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        txtID.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtID.setText("[ID]");
        getContentPane().add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(329, 81, 199, -1));

        jLabel6.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        jLabel6.setText("Question");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 131, 199, -1));

        opt4Field.setFont(new java.awt.Font("Montserrat", 0, 16)); // NOI18N
        opt4Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt4FieldActionPerformed(evt);
            }
        });
        getContentPane().add(opt4Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 464, 451, 40));

        jLabel7.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        jLabel7.setText("Options");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 227, 199, -1));

        rad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad1ActionPerformed(evt);
            }
        });
        getContentPane().add(rad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 277, -1, -1));

        rad2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad2ActionPerformed(evt);
            }
        });
        getContentPane().add(rad2, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 344, -1, -1));

        rad3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad3ActionPerformed(evt);
            }
        });
        getContentPane().add(rad3, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 412, -1, -1));

        rad4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad4ActionPerformed(evt);
            }
        });
        getContentPane().add(rad4, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 473, -1, -1));

        questionField.setFont(new java.awt.Font("Montserrat", 0, 16)); // NOI18N
        questionField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                questionFieldActionPerformed(evt);
            }
        });
        getContentPane().add(questionField, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 167, 497, 40));

        opt2Field.setFont(new java.awt.Font("Montserrat", 0, 16)); // NOI18N
        opt2Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt2FieldActionPerformed(evt);
            }
        });
        getContentPane().add(opt2Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 334, 451, 40));

        opt1Field.setFont(new java.awt.Font("Montserrat", 0, 16)); // NOI18N
        opt1Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt1FieldActionPerformed(evt);
            }
        });
        getContentPane().add(opt1Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 268, 450, 40));

        opt3Field.setFont(new java.awt.Font("Montserrat", 0, 16)); // NOI18N
        opt3Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt3FieldActionPerformed(evt);
            }
        });
        getContentPane().add(opt3Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 403, 451, 40));

        OKButton.setText("ok");
        OKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKButtonActionPerformed(evt);
            }
        });
        getContentPane().add(OKButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 540, 70, -1));

        backButton.setText("back");
        getContentPane().add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 70, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void opt4FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt4FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opt4FieldActionPerformed

    private void rad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rad1ActionPerformed

    private void rad2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rad2ActionPerformed

    private void rad3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rad3ActionPerformed

    private void rad4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rad4ActionPerformed

    private void questionFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_questionFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_questionFieldActionPerformed

    private void opt2FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt2FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opt2FieldActionPerformed

    private void opt1FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt1FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opt1FieldActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void opt3FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt3FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opt3FieldActionPerformed

    private void OKButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKButtonActionPerformed
        setVisible(false);
        new AdminHome().setVisible(true);
    }//GEN-LAST:event_OKButtonActionPerformed

    private void OKbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OKbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addNewQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addNewQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addNewQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addNewQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addNewQuestion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private App.ButtonCustom OKButton;
    private App.ButtonCustom backButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField opt1Field;
    private javax.swing.JTextField opt2Field;
    private javax.swing.JTextField opt3Field;
    private javax.swing.JTextField opt4Field;
    private javax.swing.JTextField questionField;
    private javax.swing.JRadioButton rad1;
    private javax.swing.JRadioButton rad2;
    private javax.swing.JRadioButton rad3;
    private javax.swing.JRadioButton rad4;
    private javax.swing.JLabel txtID;
    private javax.swing.JLabel txtnum;
    // End of variables declaration//GEN-END:variables
}
