/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package App;

import DatabaseConnection.ConnectionProvider;
import java.awt.Color;
import java.awt.Point;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.AbstractAction;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.KeyStroke;

/**
 *
 * @author Asus
 */
public class EditQuestion extends javax.swing.JFrame {
    private LinkedlistBenchmark quizList;
    private String quizid;
    private static Question current_question;
    /**
     * Creates new form AddQuest
     */
    public EditQuestion() {
        initComponents();
        myinit();
    }
    
    public EditQuestion(LinkedlistBenchmark quizList, String quizid) {
        this.quizList = quizList;
        this.quizid = quizid;
        initComponents();
        myinit();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private void myinit(){
        setTitle("Edit Question");
        getContentPane().setBackground(Color.white);
        setResizable(false);
        
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        opt4Field = new RoundJTextField(15);
        jLabel7 = new javax.swing.JLabel();
        rad1 = new javax.swing.JRadioButton();
        rad2 = new javax.swing.JRadioButton();
        rad3 = new javax.swing.JRadioButton();
        rad4 = new javax.swing.JRadioButton();
        questionField = new RoundJTextField(15);
        opt2Field = new RoundJTextField(15);
        opt1Field = new RoundJTextField(15);
        opt3Field = new RoundJTextField(15);
        backButton = new App.ButtonCustom();
        OKbutton = new App.ButtonCustom();
        idField = new RoundJTextField(15);
        search_id = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtnum = new javax.swing.JLabel();
        btnGrp = new javax.swing.ButtonGroup();
        txtcounter = new javax.swing.JLabel();
        
        btnGrp.add(rad1);
        btnGrp.add(rad2);
        btnGrp.add(rad3);
        btnGrp.add(rad4);
        
        checkmark = new javax.swing.JLabel();
        checkmarkIcon = new javax.swing.ImageIcon("src/App/img/checkmark.png");
        checkmark.setIcon(checkmarkIcon);

        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                // Custom close operation logic
                int option = JOptionPane.showConfirmDialog(getContentPane(), "Are you sure you want to end editing? Your changes will not be saved.", null, JOptionPane.YES_NO_OPTION);
                if (option == JOptionPane.YES_OPTION) {
                    setVisible(false);
                    EditQuiz.open = 0;
                } 
            }
        });
        
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 255, 255));
        setBounds(new java.awt.Rectangle(0, 0, 540, 700));
        setFocusable(false);
        setForeground(java.awt.Color.white);
        setMinimumSize(new java.awt.Dimension(540, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Montserrat SemiBold", 0, 36)); // NOI18N
        jLabel1.setText("<html><u>EDIT QUESTION</u></html>");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 13, -1, -1));

        jLabel3.setFont(new java.awt.Font("Montserrat SemiBold", 0, 22)); // NOI18N
        jLabel3.setText("Input Question ID");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 87, -1, -1));

        jLabel6.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        jLabel6.setText("Question");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 184, 90, -1));

        opt4Field.setFont(new java.awt.Font("Montserrat", 0, 16)); // NOI18N
        getContentPane().add(opt4Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 524, 451, 40));

        jLabel7.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        jLabel7.setText("Options");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 283, 91, -1));

        rad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad1ActionPerformed(evt);
            }
        });
        getContentPane().add(rad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 321, -1, -1));

        rad2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad2ActionPerformed(evt);
            }
        });
        getContentPane().add(rad2, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 396, -1, -1));

        rad3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad3ActionPerformed(evt);
            }
        });
        getContentPane().add(rad3, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 464, -1, -1));

        rad4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad4ActionPerformed(evt);
            }
        });
        getContentPane().add(rad4, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 532, -1, -1));

        questionField.setFont(new java.awt.Font("Montserrat", 0, 16)); // NOI18N
        getContentPane().add(questionField, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 214, 497, 40));

        opt2Field.setFont(new java.awt.Font("Montserrat", 0, 16)); // NOI18N
        getContentPane().add(opt2Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 386, 451, 40));
        opt1Field.setFont(new java.awt.Font("Montserrat", 0, 16)); // NOI18N
        getContentPane().add(opt1Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 313, 450, 40));

        opt3Field.setFont(new java.awt.Font("Montserrat", 0, 16)); // NOI18N
        getContentPane().add(opt3Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 456, 451, 40));

        backButton.setText("Back");
        backButton.setBackground(new java.awt.Color(255, 255, 255));
        backButton.setForeground(new java.awt.Color(57, 129, 247));
        backButton.setBorderColor(new java.awt.Color(57,129,247));
        backButton.setBorderColorNotOver(new java.awt.Color(57,129,247));
        backButton.setBorderColorOver(new java.awt.Color(41, 103, 197));
        backButton.setColor(java.awt.Color.white);
        backButton.setColor2(new java.awt.Color(57, 129, 247));
        backButton.setColorClick(new java.awt.Color(235, 235, 235));
        backButton.setColorClick2(new java.awt.Color(41, 103, 197));
        backButton.setColorOver(new java.awt.Color(235, 235, 235));
        backButton.setColorOver2(new java.awt.Color(41, 103, 197));
        backButton.setFont(new java.awt.Font("Montserrat SemiBold", 0, 20)); // NOI18N
        backButton.setMaximumSize(new java.awt.Dimension(143, 68));
        backButton.setMinimumSize(new java.awt.Dimension(143, 68));
        backButton.setPreferredSize(new java.awt.Dimension(143, 68));
        backButton.setRadius(10);
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 590, 80, 50));

        OKbutton.setBackground(new java.awt.Color(57, 129, 247));
        OKbutton.setForeground(new java.awt.Color(255, 255, 255));
        OKbutton.setText("OK");
        OKbutton.setBorderColor(new java.awt.Color(57, 129, 247));
        OKbutton.setBorderColorNotOver(new java.awt.Color(57, 129, 247));
        OKbutton.setBorderColorOver(new java.awt.Color(57, 158, 255));
        OKbutton.setColor(new java.awt.Color(57, 129, 247));
        OKbutton.setColor2(java.awt.Color.white);
        OKbutton.setColorClick(new java.awt.Color(57, 158, 255));
        OKbutton.setColorClick2(java.awt.Color.white);
        OKbutton.setColorOver(new java.awt.Color(57, 158, 255));
        OKbutton.setColorOver2(java.awt.Color.white);
        OKbutton.setFont(new java.awt.Font("Montserrat SemiBold", 0, 20)); // NOI18N
        OKbutton.setMaximumSize(new java.awt.Dimension(143, 68));
        OKbutton.setMinimumSize(new java.awt.Dimension(143, 68));
        OKbutton.setPreferredSize(new java.awt.Dimension(143, 68));
        OKbutton.setRadius(10);
        OKbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(OKbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 590, 80, 50));

        idField.setFont(new java.awt.Font("Montserrat", 0, 16)); // NOI18N
        idField.getInputMap(JComponent.WHEN_FOCUSED).put(KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0), "enterPressed");
        idField.getActionMap().put("enterPressed", new AbstractAction() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent e) {
                handleSearchID();
            }
        });
        getContentPane().add(idField, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 83, 140, 40));
        
        jLabel4.setFont(new java.awt.Font("Montserrat SemiBold", 0, 22)); // NOI18N
        jLabel4.setText("Question");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 149, -1, -1));

        txtnum.setFont(new java.awt.Font("Montserrat SemiBold", 0, 20)); // NOI18N
        txtnum.setText("[num]");
        getContentPane().add(txtnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 151, 100, -1));

        txtcounter.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        txtcounter.setText("(0 / 100)");
        getContentPane().add(txtcounter, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, -1, 30));
        
        search_id.setIcon(new javax.swing.ImageIcon("src/App/img/search_id.png"));
        search_id.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                handleSearchID();
            }
            
            @Override
            public void mouseEntered(MouseEvent e) {
                search_id.setIcon(new javax.swing.ImageIcon("src/App/img/search_id_hover.png"));
            }

            @Override
            public void mouseExited(MouseEvent e) {
                search_id.setIcon(new javax.swing.ImageIcon("src/App/img/search_id.png"));
            }
        }); 
        getContentPane().add(search_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 83, 37, -1));
       
        pack();
        setLocationRelativeTo(null);
    }
    
    private void handleSearchID(){
        String idStr = idField.getText();
        Linkedlist.Node current_node = quizList.quiz.getNode(idStr);

        if(current_node != null){
           current_question = current_node.data; 
           txtnum.setText(Integer.toString(current_question.getQuestionNumber()));
           questionField.setText(current_question.getQuestion());
           opt1Field.setText(current_question.getOption1());
           opt2Field.setText(current_question.getOption2());
           opt3Field.setText(current_question.getOption3());
           opt4Field.setText(current_question.getOption4());

           if (current_question.getOption1().equals(current_question.getCorrectAnswer())){
                rad1.setSelected(true);
                drawCheckmark(rad1, checkmark, checkmarkIcon);
            }
            else if (current_question.getOption2().equals(current_question.getCorrectAnswer())){
                rad2.setSelected(true);
                drawCheckmark(rad2, checkmark, checkmarkIcon);
            }
            else if (current_question.getOption3().equals(current_question.getCorrectAnswer())){
                rad3.setSelected(true);
                drawCheckmark(rad3, checkmark, checkmarkIcon);
            }
            else if (current_question.getOption4().equals(current_question.getCorrectAnswer())){
                rad4.setSelected(true);
                drawCheckmark(rad4, checkmark, checkmarkIcon);
            }                  

        }else{
            String message = "There is no question with the ID of " + idStr;
            JOptionPane.showMessageDialog(getContentPane(), message);
        }
    }
    
    private void drawCheckmark(JRadioButton radio, JLabel checkmark, ImageIcon checkmarkIcon){
        //set the previous checkmark (if any) to false first
        checkmark.setVisible(false);
        
        //find radio button location
        Point radioLocation = radio.getLocation();
        int checkmarkX = radioLocation.x; 
        int checkmarkY = radioLocation.y; 

        // Set the bounds of the checkmark label
        checkmark.setBounds(checkmarkX, checkmarkY, checkmarkIcon.getIconWidth(), checkmarkIcon.getIconHeight());

        // Add the checkmark label to the parent container of the radio button
        getContentPane().add(checkmark, new org.netbeans.lib.awtextra.AbsoluteConstraints(radio.getX(), radio.getY(), 17, 17));
        
        //set the checkmark z index to be the top layer
        getContentPane().setComponentZOrder(checkmark, 0);
        //set the checkmark to be visible in the new location
        checkmark.setVisible(true);        
        getContentPane().repaint();
    }                                        

    private void rad1ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
        drawCheckmark(rad1, checkmark, checkmarkIcon);
    }                                    

    private void rad2ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
        drawCheckmark(rad2, checkmark, checkmarkIcon);
    }                                    

    private void rad3ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
        drawCheckmark(rad3, checkmark, checkmarkIcon);
    }                                    

    private void rad4ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
        drawCheckmark(rad4, checkmark, checkmarkIcon);
    }                                           

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {                                           
        int option = JOptionPane.showConfirmDialog(getContentPane(), "Are you sure you want to end editing? Your changes will not be saved.", null, JOptionPane.YES_NO_OPTION);
        if (option == JOptionPane.YES_OPTION) {
            setVisible(false);
            EditQuiz.open = 0;
        }        
    }                                          

    private void OKbuttonActionPerformed(java.awt.event.ActionEvent evt) {                                         
        String questionStr = questionField.getText();
        String opt1Str = opt1Field.getText();
        String opt2Str = opt2Field.getText();
        String opt3Str = opt3Field.getText();
        String opt4Str = opt4Field.getText();      
        String answerStr = "";
        
        if (rad1.isSelected()){
            answerStr = opt1Str;
        }
        else if (rad2.isSelected()){
            answerStr = opt2Str;
        } 
        else if (rad3.isSelected()){
            answerStr = opt3Str;
        }
        else if (rad4.isSelected()){
            answerStr = opt4Str;
        }
        
        
        if(questionStr.equals("")){
            JOptionPane.showMessageDialog(getContentPane(), "Question is still empty.");
        }
        else if (opt1Str.equals("")){
            JOptionPane.showMessageDialog(getContentPane(), "Option 1 is still empty.");
        }
        else if (opt2Str.equals("")){
            JOptionPane.showMessageDialog(getContentPane(), "Option 2 is still empty.");
        }
        else if (opt3Str.equals("")){
            JOptionPane.showMessageDialog(getContentPane(), "Option 3 is still empty.");
        }
        else if (opt4Str.equals("")){
            JOptionPane.showMessageDialog(getContentPane(), "Option 4 is still empty.");
        }
        else if (answerStr.equals("")){
            JOptionPane.showMessageDialog(getContentPane(),"Please choose the correct answer.");
        }
        else{
            try{
                //edit in linkedlist
                String idStr = current_question.getQuestionID();
                EditQuiz.quizlist.editQuestion(idStr, questionStr, answerStr, opt1Str, opt2Str, opt3Str, opt4Str);
                
                //edit in database
                Connection con = ConnectionProvider.getCon();
                String query = "UPDATE question SET question = ?, answer = ?, option1 = ?, option2 = ?, option3 = ?, option4 = ? WHERE id = ?";
                PreparedStatement ps = con.prepareStatement(query);
                
                ps.setString(1, questionStr);
                ps.setString(2, answerStr);
                ps.setString(3, opt1Str);
                ps.setString(4, opt2Str);
                ps.setString(5, opt3Str);
                ps.setString(6, opt4Str);
                ps.setString(7, idStr);
                
                ps.executeUpdate();
                
                //show message and close menu
                System.out.println("==========================================");
                EditQuiz.quizlist.printQuestions();
                String message = "Question with the ID of "+ idStr +" edited successfully.";
                JOptionPane.showMessageDialog(getContentPane(), message);
                
                current_question = null;
                setVisible(false);
                EditQuiz.open = 0;
                

            }catch(Exception e){
                JOptionPane.showMessageDialog(getContentPane(), e);
            }                 
            
        }
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditQuestion().setVisible(true);
            }
        });
    }
    
    private App.ButtonCustom OKbutton;
    private App.ButtonCustom backButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField opt1Field;
    private javax.swing.JTextField opt2Field;
    private javax.swing.JTextField opt3Field;
    private javax.swing.JTextField opt4Field;
    private javax.swing.JTextField questionField;
    private javax.swing.JRadioButton rad1;
    private javax.swing.JRadioButton rad2;
    private javax.swing.JRadioButton rad3;
    private javax.swing.JRadioButton rad4;
    private javax.swing.JTextField idField;
    private javax.swing.JLabel search_id;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel txtnum;
    private javax.swing.JLabel txtcounter;
    private javax.swing.ButtonGroup btnGrp;
    private javax.swing.JLabel checkmark;
    private javax.swing.ImageIcon checkmarkIcon;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
