/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package App;

/**
 *
 * @author asus
 */
public class WelcomePage extends javax.swing.JFrame {

    /**
     * Creates new form WelcomePage
     */
    public WelcomePage() {
        initComponents();
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        signUpButton = new App.buttonCustom();
        logInButton = new App.buttonCustom();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        signUpButton.setBackground(new java.awt.Color(255, 255, 255));
        signUpButton.setText("Sign Up");
        signUpButton.setBorderColor(new java.awt.Color(102, 102, 102));
        signUpButton.setBorderColorNotOver(new java.awt.Color(102, 102, 102));
        signUpButton.setBorderColorOver(new java.awt.Color(0, 0, 0));
        signUpButton.setColor(java.awt.Color.white);
        signUpButton.setColor2(new java.awt.Color(0, 0, 0));
        signUpButton.setColorClick(new java.awt.Color(235, 235, 235));
        signUpButton.setColorClick2(java.awt.Color.black);
        signUpButton.setColorOver(new java.awt.Color(235, 235, 235));
        signUpButton.setColorOver2(java.awt.Color.black);
        signUpButton.setFont(new java.awt.Font("Montserrat SemiBold", 0, 48)); // NOI18N
        signUpButton.setRadius(80);
        signUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpButtonActionPerformed(evt);
            }
        });
        getContentPane().add(signUpButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, 710, 100));

        logInButton.setBackground(new java.awt.Color(255, 255, 255));
        logInButton.setText("Login");
        logInButton.setBorderColor(new java.awt.Color(102, 102, 102));
        logInButton.setBorderColorNotOver(new java.awt.Color(102, 102, 102));
        logInButton.setBorderColorOver(new java.awt.Color(0, 0, 0));
        logInButton.setColor(java.awt.Color.white);
        logInButton.setColor2(java.awt.Color.black);
        logInButton.setColorClick(new java.awt.Color(235, 235, 235));
        logInButton.setColorClick2(java.awt.Color.black);
        logInButton.setColorOver(new java.awt.Color(235, 235, 235));
        logInButton.setColorOver2(java.awt.Color.black);
        logInButton.setFont(new java.awt.Font("Montserrat SemiBold", 0, 48)); // NOI18N
        logInButton.setRadius(80);
        logInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logInButtonActionPerformed(evt);
            }
        });
        getContentPane().add(logInButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 510, 710, 100));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App/img/background_welcome.png"))); // NOI18N
        bg.setText("jLabel1");
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, -1));
        bg.getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void signUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpButtonActionPerformed
        setVisible(false);
        new SignUpPage().setVisible(true);
    }//GEN-LAST:event_signUpButtonActionPerformed

    private void logInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logInButtonActionPerformed
        setVisible(false);
        new loginPage().setVisible(true);
    }//GEN-LAST:event_logInButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WelcomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WelcomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WelcomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WelcomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WelcomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private App.buttonCustom logInButton;
    private App.buttonCustom signUpButton;
    // End of variables declaration//GEN-END:variables
}
